title: "Notes"
description: "My Learning Notes"

theme: null

remote_theme: abhinavs/moonwalk

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

include:
  - assets
