title: "Notes"
description: "My Learning Notes"

remote_theme: pages-themes/hacker@v0.2.0

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

include:
  - assets
